version: "3"
services:
  db2xmeta:
    image: 921992833788.dkr.ecr.us-west-2.amazonaws.com/db2xmeta:8.23
    ports:
      - "50000:50000"
	  - "55000:55000"
    privileged: true
    hostname: is-xmetadocker
